### PR TITLE
add notice regarding AIO

### PR DESCRIPTION
**Pull request by szaimen**

### CODE REVIEW

**Comment by marcelklehr** [comment]
Does localAI actually have LLMs that are multilingual?

**Comment by szaimen** [comment]
> Does localAI actually have LLMs that are multilingual?

I guess so see https://github.com/go-skynet/model-gallery/blob/main/index.yaml

**Comment by marcelklehr** [comment]
i heavily doubt it. To my knowledge there are no multilingual open source llms out there atm. integration_openai will simply query the llm to simulate machine translation, so this will fail with localAI, afaict

**Comment by szaimen** [comment]
I see. However the models of the translate app could potentially be used via local AI, right?

**Comment by szaimen** [comment]
> How do you come to that conclusion?

Because local AI uses debian as base. So why should it not be possible?

**Comment by szaimen** [comment]
> Well, sure it can be implemented, but localAI only implements a subset of the models available on huggingface, AFAIK. See [localai.io/model-compatibility](https://localai.io/model-compatibility/) - The Opus models by University Helsinki are using a Marian-NMT architecture which is not in that list.

all right

**Comment by marcelklehr** [comment]
You could add the libretranslate container and integration to AIO, though.

**Comment by szaimen** [comment]
> You could add the libretranslate container and integration to AIO, though.

ah you mean as community container? Good idea!

**Pull request closed without merging**
